### ISSUE TITLE
Activation successful with errors

### ISSUE THREAD

**Issue by ram0ng1** [frontend-garden/frontend-garden-ghost-theme#69]
I managed to activate the theme, but with errors...

Could you help me with the problem?

![image](https://user-images.githubusercontent.com/13917322/144510016-5065b94a-5e56-4784-b02d-38bcd55927b6.png)

**Comment by adamkudrna** [comment]
@ram0ng1 Have you compiled the source? All [mandatory classes](https://github.com/frontend-garden/frontend-garden-ghost-theme/blob/main/assets/scss/styles/06-koenig/_sizes.scss) are present in output CSS.

Please keep in mind this theme is designed solely for the purposes of the [Frontend.Garden](https://frontend.garden) magazine that I run. [Fell free](https://github.com/frontend-garden/frontend-garden-ghost-theme/blob/main/LICENSE.md) to try the theme and use it as a source of inspiration, however it's not intended to work out-of-the-box for any projects other than FG 🍀.
